// this is generated by v0

"use client";

import Link from "next/link";
import Image from "next/image";
import { useState, useRef, useEffect } from "react";
import {
  Headphones,
  Radio,
  Play,
  ChevronRight,
  ArrowRight,
  Menu,
  X,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

export default function Home() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const [menuHeight, setMenuHeight] = useState<number | undefined>(undefined);

  useEffect(() => {
    if (menuRef.current) {
      setMenuHeight(menuRef.current.scrollHeight);
    }
  }, [mobileMenuOpen]);

  return (
    <div className="flex min-h-screen flex-col">
      {/* Header */}
      <header className="sticky top-0 z-40 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center justify-between">
          <div className="flex items-center gap-2">
            <Radio className="h-6 w-6 text-rose-600" />
            <span className="text-xl font-bold">RadioWave</span>
          </div>

          <nav className="hidden md:flex gap-6">
            <Link
              href="#"
              className="text-sm font-medium transition-colors hover:text-primary"
            >
              Home
            </Link>
            <Link
              href="#news"
              className="text-sm font-medium transition-colors hover:text-primary"
            >
              News
            </Link>
            <Link
              href="#shows"
              className="text-sm font-medium transition-colors hover:text-primary"
            >
              Shows
            </Link>
            <Link
              href="#groups"
              className="text-sm font-medium transition-colors hover:text-primary"
            >
              Groups
            </Link>
            <Link
              href="#events"
              className="text-sm font-medium transition-colors hover:text-primary"
            >
              Events
            </Link>
            <Link
              href="#contact"
              className="text-sm font-medium transition-colors hover:text-primary"
            >
              Contact
            </Link>
          </nav>

          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              className="md:hidden"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? (
                <X className="h-5 w-5" />
              ) : (
                <Menu className="h-5 w-5" />
              )}
              <span className="sr-only">Toggle menu</span>
            </Button>
            <Button className="hidden md:flex gap-2 bg-rose-600 hover:bg-rose-700">
              <Play className="h-4 w-4" />
              Listen Live
            </Button>
          </div>
        </div>

        {/* Mobile Menu Dropdown */}
        <div
          className={cn(
            "md:hidden border-t border-gray-200 bg-white overflow-hidden transition-all duration-300 ease-in-out",
            mobileMenuOpen ? "opacity-100" : "opacity-0 max-h-0"
          )}
          style={{ maxHeight: mobileMenuOpen ? menuHeight : 0 }}
          ref={menuRef}
        >
          <div
            className={cn(
              "container py-4 transform transition-transform duration-300",
              mobileMenuOpen ? "translate-y-0" : "-translate-y-4"
            )}
          >
            <nav className="flex flex-col gap-4 mb-6">
              <Link
                href="#"
                className="text-base font-medium transition-colors hover:text-rose-600 flex items-center py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Home
              </Link>
              <Link
                href="#news"
                className="text-base font-medium transition-colors hover:text-rose-600 flex items-center py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                News
              </Link>
              <Link
                href="#shows"
                className="text-base font-medium transition-colors hover:text-rose-600 flex items-center py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Shows
              </Link>
              <Link
                href="#groups"
                className="text-base font-medium transition-colors hover:text-rose-600 flex items-center py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Groups
              </Link>
              <Link
                href="#events"
                className="text-base font-medium transition-colors hover:text-rose-600 flex items-center py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Events
              </Link>
              <Link
                href="#contact"
                className="text-base font-medium transition-colors hover:text-rose-600 flex items-center py-2"
                onClick={() => setMobileMenuOpen(false)}
              >
                Contact
              </Link>
            </nav>

            <Button className="w-full bg-rose-600 hover:bg-rose-700 mb-6">
              <Play className="mr-2 h-4 w-4" />
              Listen Live
            </Button>

            <div className="border-t border-gray-200 pt-4">
              <h3 className="text-lg font-bold mb-3">Our Shows</h3>
              <div className="grid grid-cols-2 gap-y-2">
                <Link
                  href="#group-1"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Morning Crew
                </Link>
                <Link
                  href="#group-2"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Afternoon Vibes
                </Link>
                <Link
                  href="#group-3"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Evening Mix
                </Link>
                <Link
                  href="#group-4"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Weekend Special
                </Link>
                <Link
                  href="#group-5"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Late Night
                </Link>
                <Link
                  href="#group-6"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Jazz Hour
                </Link>
                <Link
                  href="#group-7"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Rock Classics
                </Link>
                <Link
                  href="#group-8"
                  className="text-sm hover:text-rose-600"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Sunday Unplugged
                </Link>
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative">
          <div className="absolute inset-0 bg-gradient-to-r from-rose-600/90 to-purple-800/90 z-10" />
          <Image
            src="/placeholder.svg?height=600&width=1200"
            alt="Radio station"
            width={1200}
            height={600}
            className="w-full h-[400px] object-cover"
          />
          <div className="container relative z-20 flex flex-col items-center justify-center h-[400px] text-white text-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-4">
              Your Sound, Your Station
            </h1>
            <p className="text-lg md:text-xl max-w-2xl mb-8">
              Bringing you the best music, news, and entertainment 24/7
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button
                size="lg"
                className="bg-white text-rose-600 hover:bg-gray-100"
              >
                <Headphones className="mr-2 h-5 w-5" /> Listen Now
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="border-white text-white hover:bg-white/20"
              >
                View Schedule
              </Button>
            </div>
          </div>
        </section>

        {/* News Section */}
        <section id="news" className="py-16 container">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-3xl font-bold">Latest News</h2>
            <Link
              href="#"
              className="text-rose-600 hover:underline flex items-center"
            >
              View All News <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {[
              {
                title: "New Morning Show Host Announced",
                date: "June 10, 2023",
                image: "/placeholder.svg?height=200&width=300",
                excerpt:
                  "We're excited to welcome Jane Smith as our new morning show host starting next month. Jane brings over 10 years of radio experience and a passion for connecting with listeners.",
              },
              {
                title: "Summer Concert Series Lineup Revealed",
                date: "June 8, 2023",
                image: "/placeholder.svg?height=200&width=300",
                excerpt:
                  "Check out the amazing artists performing in our annual summer concert series. This year's lineup features both established stars and exciting new talent from across the music spectrum.",
              },
            ].map((news, index) => (
              <Card key={index} className="overflow-hidden h-full">
                <div className="flex flex-col sm:flex-row h-full">
                  <div className="sm:w-2/5 lg:w-1/3">
                    <Image
                      src={news.image || "/placeholder.svg"}
                      alt={news.title}
                      width={300}
                      height={200}
                      className="w-full h-48 sm:h-full object-cover"
                    />
                  </div>
                  <div className="sm:w-3/5 lg:w-2/3 p-4 sm:p-5 flex flex-col">
                    <CardTitle className="text-lg sm:text-xl mb-2">
                      {news.title}
                    </CardTitle>
                    <CardDescription className="text-sm text-muted-foreground mb-2">
                      {news.date}
                    </CardDescription>
                    <p className="text-sm mb-4 flex-1">{news.excerpt}</p>
                    <Button
                      variant="ghost"
                      className="text-rose-600 p-0 hover:bg-transparent hover:text-rose-700 self-start"
                    >
                      Read More <ChevronRight className="ml-1 h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Radio className="h-6 w-6 text-rose-500" />
                <span className="text-xl font-bold">RadioWave</span>
              </div>
              <p className="text-gray-400 mb-4">
                Your premier destination for music, news, and entertainment.
              </p>
              <div className="flex gap-4">
                <Button
                  variant="ghost"
                  size="icon"
                  className="text-gray-400 hover:text-white"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="lucide lucide-facebook"
                  >
                    <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
                  </svg>
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="text-gray-400 hover:text-white"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="lucide lucide-twitter"
                  >
                    <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
                  </svg>
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="text-gray-400 hover:text-white"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="lucide lucide-instagram"
                  >
                    <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
                    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
                    <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
                  </svg>
                </Button>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-bold mb-4">Quick Links</h3>
              <ul className="space-y-2">
                <li>
                  <Link href="#" className="text-gray-400 hover:text-white">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="#news" className="text-gray-400 hover:text-white">
                    News
                  </Link>
                </li>
                <li>
                  <Link
                    href="#shows"
                    className="text-gray-400 hover:text-white"
                  >
                    Shows
                  </Link>
                </li>
                <li>
                  <Link
                    href="#contact"
                    className="text-gray-400 hover:text-white"
                  >
                    Contact
                  </Link>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="text-lg font-bold mb-4">Our Shows</h3>
              <ul className="space-y-2">
                <li>
                  <Link
                    href="#group-1"
                    className="text-gray-400 hover:text-white"
                  >
                    Morning Crew
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-2"
                    className="text-gray-400 hover:text-white"
                  >
                    Afternoon Vibes
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-3"
                    className="text-gray-400 hover:text-white"
                  >
                    Evening Mix
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-4"
                    className="text-gray-400 hover:text-white"
                  >
                    Weekend Special
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-5"
                    className="text-gray-400 hover:text-white"
                  >
                    Late Night
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-6"
                    className="text-gray-400 hover:text-white"
                  >
                    Jazz Hour
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-7"
                    className="text-gray-400 hover:text-white"
                  >
                    Rock Classics
                  </Link>
                </li>
                <li>
                  <Link
                    href="#group-8"
                    className="text-gray-400 hover:text-white"
                  >
                    Sunday Unplugged
                  </Link>
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
            <p>
              &copy; {new Date().getFullYear()} RadioWave. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
